package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePdfimage<M extends BasePdfimage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setFilename(java.lang.String filename) {
		set("filename", filename);
	}

	public java.lang.String getFilename() {
		return get("filename");
	}

	public void setPage(java.lang.Integer page) {
		set("page", page);
	}

	public java.lang.Integer getPage() {
		return get("page");
	}

	public void setPagesize(java.lang.Integer pagesize) {
		set("pagesize", pagesize);
	}

	public java.lang.Integer getPagesize() {
		return get("pagesize");
	}

	public void setImage(byte[] image) {
		set("image", image);
	}

	public byte[] getImage() {
		return get("image");
	}

}
