package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTeacherno(java.lang.String teacherno) {
		set("teacherno", teacherno);
	}

	public java.lang.String getTeacherno() {
		return get("teacherno");
	}

	public void setTeachername(java.lang.String teachername) {
		set("teachername", teachername);
	}

	public java.lang.String getTeachername() {
		return get("teachername");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setSchool(java.lang.String school) {
		set("school", school);
	}

	public java.lang.String getSchool() {
		return get("school");
	}

	public void setMajor(java.lang.String major) {
		set("major", major);
	}

	public java.lang.String getMajor() {
		return get("major");
	}

	public void setEducationlevel(java.lang.String educationlevel) {
		set("educationlevel", educationlevel);
	}

	public java.lang.String getEducationlevel() {
		return get("educationlevel");
	}

	public void setJobtitle(java.lang.String jobtitle) {
		set("jobtitle", jobtitle);
	}

	public java.lang.String getJobtitle() {
		return get("jobtitle");
	}

}
