package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseType<M extends BaseType<M>> extends Model<M> implements IBean {

	public void setTypeCode(java.lang.String typeCode) {
		set("type_code", typeCode);
	}

	public java.lang.String getTypeCode() {
		return get("type_code");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setIfuser(java.lang.Integer ifuser) {
		set("ifuser", ifuser);
	}

	public java.lang.Integer getIfuser() {
		return get("ifuser");
	}

}
