package com.demo.common.model;

import com.demo.common.model.base.BaseUpload;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Upload extends BaseUpload<Upload> {
	public static final Upload dao = new Upload();
	
	
	public Page<Upload> paginate(int pageNumber, int pageSize,String role,String username) {
		StringBuilder sql=new StringBuilder("select t.id,b.type type,c.title,t.score ,d.realname username,t.realfilename,t.uploadtime " +
											"from upload t ,type b, title c,user d " +
											"where t.title=c.tid and t.type=b.type_code and t.username=d.username and t.ndelete='0'");
		if(role.equals("1")){
			sql.append(" and t.username="+"'"+username+"'");
		}else if(role.equals("2")){
			//sql.append(" and c.username="+"'"+username+"'");
		}
		return paginate(pageNumber, pageSize, sql.toString());
	}
	
	public long submitCount(String username){
		return Db.queryLong("select count(1) from upload where ndelete='0' and username="+"'"+username+"'");
	}

	public Page<Upload> paginateByCondition(Integer pageNumber, int pageSize,
			 String author) {
		StringBuilder sql=new StringBuilder("select t.id,b.type type,c.title,t.score ,d.realname username,t.realfilename,t.uploadtime " +
				"from upload t ,type b, title c,user d " +
				"where t.title=c.tid and t.type=b.type_code and t.username=d.username and t.ndelete='0'");
			if(author!=null){
				sql.append("and d.realname like"+"'%"+author+"%'");
			}
		return paginate(pageNumber, pageSize, sql.toString());
	}
}
